#!/bin/bash

#  Copyright (C) 2015-2019  Rafael Senties Martinelli
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

ANDROMEDA_VERSION="Dev2019"
NUMBER_OF_STEPS=2

if [ "$EUID" -ne 0 ]
  then echo -e "\e[00;31m The script must be run as root.\e[00m"
  exit
fi

echo -e "\n\e[00;33m **************************************** \e[00m"
echo -e "\e[00;33m *** Installing Andromeda v$ANDROMEDA_VERSION *** \e[00m"
echo -e "\e[00;33m **************************************** \e[00m\n"


#
# Remove previous versions
#

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR
chmod a+x ./remove
echo -e "\e[00;33m[1/$NUMBER_OF_STEPS] Removing previous versions..\e[00m"
./remove -s

#
# Start the installation
#

echo -e "\e[00;33m\n[2/$NUMBER_OF_STEPS] Installing the software files...\e[00m"


function install_files(){
    
    echo "installing: $1"
    
    install -d $1
    install -D $DIR$1/* $1
    
}


echo -e "\e[00;32m Copying the software files...\e[00m"

install_files "/usr/bin"

install_files "/usr/share/applications"

install_files "/usr/share/andromeda"
install_files "/usr/share/andromeda/view"
install_files "/usr/share/andromeda/view/CellRenderers"
install_files "/usr/share/andromeda/view/images"
install_files "/usr/share/andromeda/model"
install_files "/usr/share/andromeda/controller"

install_files "/usr/share/doc/andromeda"
install_files "/usr/share/doc/andromeda/code"

install_files "/etc/andromeda"
install_files "/etc/andromeda/pluggins"



#
#
echo -e "\e[00;32m Replacing variables...\e[00m"

sed -i "s/__ANDROMEDA_VERSION__/$ANDROMEDA_VERSION/g" "/usr/share/andromeda/view/gui.glade"


##
## End
##
echo -e "\n\e[00;33m ****************************************** \e[00m"
echo -e "\e[00;33m *** Andromeda v$ANDROMEDA_VERSION is installed *** \e[00m"
echo -e "\e[00;33m ****************************************** \e[00m\n"
